import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import swipesRouter from "./swipes";
import matchesRouter from "./matches";
import exchangesRouter from "./exchanges";
import creditsRouter from "./credits";
import gamificationRouter from "./gamification";
import nudgesRouter from "./nudges";
import notificationsRouter from "./notifications";
import analyticsRouter from "./analytics";
import ledgerRouter from "./ledger";
import chatRouter from "./chat";
import verificationRouter from "./verification";
import onboardingRouter from "./onboarding";
import aiRouter from "./ai";
import sessionsRouter from "./sessions";
import skillsRouter from "./skills";
import battlesRouter from "./battles";
import referralRouter from "./referral";
import safetyRouter from "./safety";
import lessonsRouter from "./lessons";
import portfolioRouter from "./portfolio";
import instantMatchRouter from "./instant-match";
import featureFlagsRouter from "./feature-flags";
import reelsRouter from "./reels";
import auctionsRouter from "./auctions";
import studyRoomsRouter from "./study-rooms";
import skillDnaRouter from "./skill-dna";
import challengesRouter from "./challenges";
import voiceNotesRouter from "./voice-notes";
import capsulesRouter from "./capsules";
import vouchesRouter from "./vouches";
import liveDropsRouter from "./live-drops";
import wrappedRouter from "./wrapped";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(swipesRouter);
router.use(matchesRouter);
router.use(exchangesRouter);
router.use(creditsRouter);
router.use(gamificationRouter);
router.use(nudgesRouter);
router.use(notificationsRouter);
router.use(analyticsRouter);
router.use(ledgerRouter);
router.use(chatRouter);
router.use(verificationRouter);
router.use(onboardingRouter);
router.use(aiRouter);
router.use(sessionsRouter);
router.use(skillsRouter);
router.use(battlesRouter);
router.use(referralRouter);
router.use(safetyRouter);
router.use(lessonsRouter);
router.use(portfolioRouter);
router.use(instantMatchRouter);
router.use(featureFlagsRouter);
router.use(reelsRouter);
router.use(auctionsRouter);
router.use(studyRoomsRouter);
router.use(skillDnaRouter);
router.use(challengesRouter);
router.use(voiceNotesRouter);
router.use(capsulesRouter);
router.use(vouchesRouter);
router.use(liveDropsRouter);
router.use(wrappedRouter);

export default router;
